# Generated by Django 4.2 on 2023-07-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='is_moving_down',
            field=models.BooleanField(default=False),
        ),
    ]
